M48
; DRILL file KiCad 10.0.0 date 2026-05-03T01:36:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T01:36:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X44.84Y-22.85
X44.84Y-51.35
X139.84Y-22.85
X139.84Y-51.35
T2
X18.796Y-18.796
X166.116Y-18.796
M30
